name: Sync Upstream

on:
  schedule:
    - cron: "1 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: rovast/sync-upstream-repo@v0.0.1
        with:
          upstream_repo: https://github.com/jusbrasil/pingdom-exporter
          upstream_branch: master
          downstream_branch: master
          token: ${{ secrets.PAT_TOKEN }}
